apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureapp-eta-deploy
  labels:
    app: insureapp-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insureapp-eta-app
  template:
    metadata:
      labels:
        app: insureapp-eta-app
    spec:
      containers:
      - name: insureapp-eta-container
        image: yash1999v/insureapp
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insureapp-eta-np-service
  labels:
    app: insureapp-eta-app
spec:
  selector:
    app: insureapp-eta-app

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8081
    targetPort: 8081
